#!/bin/sh
set -e

if ! mkdir -v /moodle/init 2>/dev/nul; then

  echo "Already initialized"
  
else
  
  mkdir /moodle/app /moodle/data 
  chmod +w /moodle/app /moodle/data
  
  ( cd /moodle/app
    echo "Extracting /moodle-${MOODLE_TEMPLATE_ID}"
    tar -xzf /moodle-${MOODLE_TEMPLATE_ID}.tar.gz
  )
  echo "Initializing"
  php /moodle/app/admin/cli/install.php \
         --agree-license \
         --non-interactive \
         --lang=sl \
         --dbtype=${MOODLE_DATABASE_TYPE} \
         --dbhost=${MOODLE_DATABASE_HOST} \
         --dbport=${MOODLE_DATABASE_PORT_NUMBER}\
         --dbuser=${MOODLE_DATABASE_USER}\
         --dbname=${MOODLE_DATABASE_NAME}\
         --dbpass=${MOODLE_DATABASE_PASSWORD}\
         --adminuser=${MOODLE_USERNAME} \
         --adminpass=${MOODLE_PASSWORD} \
         --wwwroot=http://${MOODLE_HOST}/ \
         --fullname="${MOODLE_FULL_NAME}" \
         --shortname="${MOODLE_SHORT_NAME}" \
         --dataroot=/moodle/data 

  chmod +r /moodle/app/config.php
  echo 'Please do not remove this file' > /moodle/init
  
fi

  
php-fpm &
exec httpd -DFOREGROUND "$@"
