---
apiVersion: v1
kind: Namespace
metadata:
  name: moodle-sys
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: libstorage
  namespace: moodle-sys
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5G
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lib
    app.kubernetes.io/component: lib
    app.kubernetes.io/instance: lib
  name: lib
  namespace: moodle-sys
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: lib
  strategy: {}
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: lib
    spec:
      containers:
      - image: registry.access.redhat.com/ubi9/httpd-24:latest
        name: lib
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        volumeMounts:
        - mountPath: /var/www/html
          name: libstorage
      volumes:
      - name: libstorage
        persistentVolumeClaim:
          claimName: libstorage   
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lib
    app.kubernetes.io/component: lib
    app.kubernetes.io/instance: lib
  name: lib
  namespace: moodle-sys
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    deployment: lib
---
