---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: awstats
  namespace: moodle-sys
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: awstats
  name: awstats
  namespace: moodle-sys
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      openshift.io/imported-from: central-quay-registry.apps.cdiul-iso.uni-lj.si/moodle/awstats:latest
    from:
      kind: DockerImage
      name: central-quay-registry.apps.cdiul-iso.uni-lj.si/moodle/awstats:latest
    importPolicy:
      importMode: Legacy
    name: latest
    referencePolicy:
      type: Source
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    image.openshift.io/triggers: "[{\"from\":{\"kind\":\"ImageStreamTag\",\"name\":\"awstats:latest\"},\"fieldPath\":\"spec.template.spec.containers[?(@.name==\\\"awstats\\\")].image\"},{\"from\":{\"kind\":\"ImageStreamTag\",\"name\":\"awstats:latest\"},\"fieldPath\":\"spec.template.spec.containers[?(@.name==\\\"httpd\\\")].image\"}]"
    app: awstats
  name: awstats
  namespace: moodle-sys
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: awstats
  template:
    metadata:
      labels:
        app: awstats
        deployment: awstats
    spec:
      containers:
      - image: ' '
        imagePullPolicy: IfNotPresent
        name: awstats
        ports:
        - containerPort: 1514
          protocol: TCP
        - containerPort: 1514
          protocol: UDP
        resources:
          requests:
            cpu: 250m
            memory: 250Mi
        volumeMounts:
        - mountPath: /awstats
          name: awstats
        env:
        - name: TZ
          value: Europe/Ljubljana
      - image: ' '
        imagePullPolicy: IfNotPresent
        name: httpd
        command: ["/usr/local/bin/httpd-foreground"]
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 250Mi
        volumeMounts:
        - mountPath: /etc/awstats
          subPath: config
          name: awstats
        - mountPath: /awstats
          name: awstats
        env:
        - name: TZ
          value: Europe/Ljubljana
      volumes:
      - name: awstats
        persistentVolumeClaim:
          claimName: awstats   
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: awstats
  name: awstats
  namespace: moodle-sys
spec:
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: 514-tcp
    port: 514
    protocol: TCP
    targetPort: 1514
  - name: 514-udp
    port: 514
    protocol: UDP
    targetPort: 1514
  selector:
    app: awstats
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: awstats
  name: awstats
  namespace: moodle-sys
spec:
  host: awstats-moodle-sys.apps.cdiul-iso.uni-lj.si
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: awstats
  tls:
    termination: edge
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app: awstats
  name: awstats
  namespace: moodle-sys
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: awstats
---
# oc adm policy add-cluster-role-to-user collect-application-logs system:serviceaccount:openshift-logging:mdlecollect
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mdlecollect
  namespace: openshift-logging
# https://access.redhat.com/articles/7089860
---
apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: mdle-awstats
  namespace: openshift-logging
# annotations:
#   observability.openshift.io/log-level: debug
spec:
  serviceAccount: 
    name: mdlecollect
  collector:
    resources:
      limits:
        memory: 16Gi
  inputs: 
    - name: apache-logs
      type: application
      application:
       selector:
         matchLabels: 
           app: mdleapp
  pipelines:
    - name: to-awastats-logs
      inputRefs:
        - apache-logs
      outputRefs:
        - awstats-logs
  outputs:
    - name: awstats-logs
      syslog:
        appName: moodle
        facility: local1
        rfc: RFC5424
        url: tcp://awstats.moodle-sys:514
      type: syslog
